### ISSUE TITLE
Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)

### ISSUE THREAD

**Issue by knight0zh** [llKYOTOll/GoogleDriveHandler#3]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
E/flutter (22408): #0      GoogleSignInApi.signIn
messages.g.dart:221
E/flutter (22408): <asynchronous suspension>
E/flutter (22408): #1      GoogleSignIn._callMethod
google_sign_in.dart:274
E/flutter (22408): <asynchronous suspension>
E/flutter (22408): #2      GoogleSignIn.signIn.isCanceled
google_sign_in.dart:408
E/flutter (22408): <asynchronous suspension>
E/flutter (22408):

**Comment by WorkWithAfridi** [comment]
Setup firebase again. This error happens when there is an issue with
Firebase integration.

**Comment by WorkWithAfridi** [comment]
Closing this issue since no new comments were added in the past 2 months.

**Comment by tailoristic** [comment]
Facing same issue, Please reopen and resolve

**Comment by WorkWithAfridi** [comment]
@tailoristic Please try setting up firebase again. "Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
" occurs when there is an issue with
Firebase integration.
